// <auto-generated />
using System;
using EduPost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPost.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduPost.Models.AYear", b =>
                {
                    b.Property<int>("YearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("year_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearId"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("begin_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("YearTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("year_title");

                    b.HasKey("YearId");

                    b.ToTable("AYear");
                });

            modelBuilder.Entity("EduPost.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<bool>("AgreeToTerms")
                        .HasColumnType("bit");

                    b.Property<string>("ArticleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("article_name");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpireDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expire_date");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("article_faculty");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ArticleId");

                    b.HasIndex("UserID");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            AgreeToTerms = true,
                            ArticleTitle = "ITArticle01",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 11, 36, 895, DateTimeKind.Unspecified).AddTicks(8253), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 11, 36, 895, DateTimeKind.Unspecified).AddTicks(9251), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Information Tecnology",
                            Public = true,
                            StatusId = 0,
                            UserID = 7
                        },
                        new
                        {
                            ArticleId = 2,
                            AgreeToTerms = true,
                            ArticleTitle = "ITArticle02",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 11, 52, 633, DateTimeKind.Unspecified).AddTicks(4713), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 11, 52, 633, DateTimeKind.Unspecified).AddTicks(4770), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Information Tecnology",
                            Public = true,
                            StatusId = 0,
                            UserID = 7
                        },
                        new
                        {
                            ArticleId = 3,
                            AgreeToTerms = true,
                            ArticleTitle = "ITArticle03",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 11, 59, 722, DateTimeKind.Unspecified).AddTicks(3506), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 11, 59, 722, DateTimeKind.Unspecified).AddTicks(3572), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Information Tecnology",
                            Public = false,
                            StatusId = 0,
                            UserID = 7
                        },
                        new
                        {
                            ArticleId = 4,
                            AgreeToTerms = true,
                            ArticleTitle = "ITArticle04",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 12, 11, 487, DateTimeKind.Unspecified).AddTicks(1948), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 12, 11, 487, DateTimeKind.Unspecified).AddTicks(2005), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Information Tecnology",
                            Public = false,
                            StatusId = 0,
                            UserID = 7
                        },
                        new
                        {
                            ArticleId = 5,
                            AgreeToTerms = true,
                            ArticleTitle = "ITArticle05",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 12, 24, 227, DateTimeKind.Unspecified).AddTicks(3664), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 12, 24, 227, DateTimeKind.Unspecified).AddTicks(3751), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Information Tecnology",
                            Public = true,
                            StatusId = 0,
                            UserID = 7
                        },
                        new
                        {
                            ArticleId = 6,
                            AgreeToTerms = true,
                            ArticleTitle = "CSArticle01",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 13, 42, 780, DateTimeKind.Unspecified).AddTicks(4099), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 13, 42, 780, DateTimeKind.Unspecified).AddTicks(4158), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Computer Science",
                            Public = true,
                            StatusId = 0,
                            UserID = 8
                        },
                        new
                        {
                            ArticleId = 7,
                            AgreeToTerms = true,
                            ArticleTitle = "CSArticle02",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 13, 50, 639, DateTimeKind.Unspecified).AddTicks(4727), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 13, 50, 639, DateTimeKind.Unspecified).AddTicks(4775), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Computer Science",
                            Public = false,
                            StatusId = 0,
                            UserID = 8
                        },
                        new
                        {
                            ArticleId = 8,
                            AgreeToTerms = true,
                            ArticleTitle = "CSArticle03",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 14, 1, 586, DateTimeKind.Unspecified).AddTicks(277), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 14, 1, 586, DateTimeKind.Unspecified).AddTicks(327), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Computer Science",
                            Public = true,
                            StatusId = 0,
                            UserID = 8
                        },
                        new
                        {
                            ArticleId = 9,
                            AgreeToTerms = true,
                            ArticleTitle = "CSArticle04",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 14, 11, 955, DateTimeKind.Unspecified).AddTicks(2979), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 14, 11, 955, DateTimeKind.Unspecified).AddTicks(3029), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Computer Science",
                            Public = true,
                            StatusId = 0,
                            UserID = 8
                        },
                        new
                        {
                            ArticleId = 10,
                            AgreeToTerms = true,
                            ArticleTitle = "EArticle01",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 15, 0, 935, DateTimeKind.Unspecified).AddTicks(7115), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 15, 0, 935, DateTimeKind.Unspecified).AddTicks(7182), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Economics",
                            Public = true,
                            StatusId = 0,
                            UserID = 9
                        },
                        new
                        {
                            ArticleId = 11,
                            AgreeToTerms = true,
                            ArticleTitle = "EArticle02",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 15, 7, 767, DateTimeKind.Unspecified).AddTicks(7437), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 15, 7, 767, DateTimeKind.Unspecified).AddTicks(7483), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Economics",
                            Public = false,
                            StatusId = 0,
                            UserID = 9
                        },
                        new
                        {
                            ArticleId = 12,
                            AgreeToTerms = true,
                            ArticleTitle = "EArticle03",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 15, 16, 422, DateTimeKind.Unspecified).AddTicks(1925), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 15, 16, 422, DateTimeKind.Unspecified).AddTicks(1982), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Economics",
                            Public = true,
                            StatusId = 0,
                            UserID = 9
                        },
                        new
                        {
                            ArticleId = 13,
                            AgreeToTerms = true,
                            ArticleTitle = "ESArticle01",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 15, 41, 591, DateTimeKind.Unspecified).AddTicks(5518), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 15, 41, 591, DateTimeKind.Unspecified).AddTicks(5631), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Environmental Science",
                            Public = true,
                            StatusId = 0,
                            UserID = 10
                        },
                        new
                        {
                            ArticleId = 14,
                            AgreeToTerms = true,
                            ArticleTitle = "ESArticle02",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 15, 50, 428, DateTimeKind.Unspecified).AddTicks(8359), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 15, 50, 428, DateTimeKind.Unspecified).AddTicks(8402), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Environmental Science",
                            Public = true,
                            StatusId = 0,
                            UserID = 10
                        },
                        new
                        {
                            ArticleId = 15,
                            AgreeToTerms = true,
                            ArticleTitle = "PsyArticle01",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 4, 2, 20, 16, 26, 676, DateTimeKind.Unspecified).AddTicks(365), new TimeSpan(0, 7, 0, 0, 0)),
                            ExpireDate = new DateTimeOffset(new DateTime(2024, 4, 16, 20, 16, 26, 676, DateTimeKind.Unspecified).AddTicks(431), new TimeSpan(0, 7, 0, 0, 0)),
                            Faculty = "Psychology",
                            Public = true,
                            StatusId = 0,
                            UserID = 11
                        });
                });

            modelBuilder.Entity("EduPost.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ArticleId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("comment_date");

                    b.Property<bool?>("IsAnon")
                        .HasColumnType("bit")
                        .HasColumnName("anonymous");

                    b.Property<bool?>("IsEdited")
                        .IsRequired()
                        .HasColumnType("bit")
                        .HasColumnName("edited");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("EduPost.Models.Faculty", b =>
                {
                    b.Property<int?>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FacultyId"));

                    b.Property<string>("FacultyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("facultyName");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty");

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            FacultyName = "Information Tecnology"
                        },
                        new
                        {
                            FacultyId = 2,
                            FacultyName = "Computer Science"
                        },
                        new
                        {
                            FacultyId = 3,
                            FacultyName = "Economics"
                        },
                        new
                        {
                            FacultyId = 4,
                            FacultyName = "Environmental Science"
                        },
                        new
                        {
                            FacultyId = 5,
                            FacultyName = "Psychology"
                        });
                });

            modelBuilder.Entity("EduPost.Models.FeedBack", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("ArticleId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("feedback_date");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ArticleId");

                    b.ToTable("FeedBack");
                });

            modelBuilder.Entity("EduPost.Models.File", b =>
                {
                    b.Property<int?>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FileId"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("FileContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_content_type");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("file_data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.HasKey("FileId");

                    b.HasIndex("ArticleId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("EduPost.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("isRead?");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("EduPost.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("roleName");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Coordinator",
                            NormalizedName = "COORDINATOR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("EduPost.Models.Status", b =>
                {
                    b.Property<int?>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("statusName");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("EduPost.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("faculty");

                    b.Property<bool?>("FirstLogin")
                        .HasColumnType("bit")
                        .HasColumnName("first_login");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61521b0c-13fb-44a0-b67c-f753cf71bba5",
                            Email = "TestEmail@email.com",
                            EmailConfirmed = true,
                            Faculty = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "TESTEMAIL@EMAIL.COM",
                            NormalizedUserName = "TESTEMAIL@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBdGZDqY/P61BXsLDI0xzUn5ZqaiwOMGgzYjGpoJKv8eMggcDxUGL2GZcoVXetrUpA==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "P326W733E2RXH66PPK4ZYOQRQREJTMUD",
                            TwoFactorEnabled = false,
                            UserName = "TestEmail@email.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d87eaa6a-5599-41b8-8ad9-a838f4f54469",
                            Email = "ITHead@email.com",
                            EmailConfirmed = true,
                            Faculty = "Information Tecnology",
                            LockoutEnabled = true,
                            NormalizedEmail = "ITHEAD@EMAIL.COM",
                            NormalizedUserName = "ITHEAD@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAQBYKWo+E7dm+Ima6pOPGomuDXZgLdRgK1tLB5TzHPj02OnEYBxtByCJATakG/mrg==",
                            PhoneNumberConfirmed = false,
                            Role = "Coordinator",
                            SecurityStamp = "44GZPSXJBR6BQBPNQYL6CLA4YJ45BLZR",
                            TwoFactorEnabled = false,
                            UserName = "ITHead@email.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c45238d0-e841-48e0-a3dc-977f99dc4ccc",
                            Email = "CSHead@email.com",
                            EmailConfirmed = true,
                            Faculty = "Computer Science",
                            LockoutEnabled = true,
                            NormalizedEmail = "CSHEAD@EMAIL.COM",
                            NormalizedUserName = "CSHEAD@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKr/dKYAC/NQ7UcliNfcOgErqZ+BSME9uFvc+pKZvd93r1IdlPCLeaLE/4TLjD0oxA==",
                            PhoneNumberConfirmed = false,
                            Role = "Coordinator",
                            SecurityStamp = "75CKF5JSM6GVN3T23KGNTDZWLZIRUHJ4",
                            TwoFactorEnabled = false,
                            UserName = "CSHead@email.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65eb5b53-ca56-486b-a259-d3298110283c",
                            Email = "EHead@email.com",
                            EmailConfirmed = true,
                            Faculty = "Economics",
                            LockoutEnabled = true,
                            NormalizedEmail = "EHEAD@EMAIL.COM",
                            NormalizedUserName = "EHEAD@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI0CPsg46g7UZPhdS4w8AblJ7Rjr6ZTAHxldpci/hdk9VDZ4ZFv8Ttm/yCqYT7+ExQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Coordinator",
                            SecurityStamp = "2QYLW55AYTFQXCNENHOBC5CV7XUWNZS2",
                            TwoFactorEnabled = false,
                            UserName = "EHead@email.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "abc639ef-d26d-41ab-966f-f7354953bc2d",
                            Email = "ESHead@email.com",
                            EmailConfirmed = true,
                            Faculty = "Environmental Science",
                            LockoutEnabled = true,
                            NormalizedEmail = "ESHEAD@EMAIL.COM",
                            NormalizedUserName = "ESHEAD@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMe25e1Gl1pCWK4HMaZxKQ8LZ0K/lrHK47jLVaEPeQM3Fsnl9QUjteNm5Lgw72mrWg==",
                            PhoneNumberConfirmed = false,
                            Role = "Coordinator",
                            SecurityStamp = "DNKIX4TEPAINNDQVTKDCVRTWOGMOA5WX",
                            TwoFactorEnabled = false,
                            UserName = "ESHead@email.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72db441f-2d91-4aac-8460-8009d80847d4",
                            Email = "PsyHead@email.com",
                            EmailConfirmed = true,
                            Faculty = "Psychology",
                            LockoutEnabled = true,
                            NormalizedEmail = "PSYHEAD@EMAIL.COM",
                            NormalizedUserName = "PSYHEAD@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIzrdjW8BK7V/nYdV6Q7czg1WqmweIn+OxF7nNSjE79gGkchJOee73gXZGyVkwu1Eg==",
                            PhoneNumberConfirmed = false,
                            Role = "Coordinator",
                            SecurityStamp = "WM5VWO55FUMUZ2WOELN73KXSFP7TIHXY",
                            TwoFactorEnabled = false,
                            UserName = "PsyHead@email.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eb09b0fb-ec00-493a-922a-dac179910c75",
                            Email = "ITUser@email.com",
                            EmailConfirmed = true,
                            Faculty = "Information Tecnology",
                            LockoutEnabled = true,
                            NormalizedEmail = "ITUSER@EMAIL.COM",
                            NormalizedUserName = "ITUSER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH+sZz3bFv5Wywum0wvsGfPWHcHzrU1eP3NFCsZgCv+i4iLsX/hbwo5UAoa5DXEY1Q==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "KL4GXYEBVQCM4CMOUHUWGVA76X5GWPLK",
                            TwoFactorEnabled = false,
                            UserName = "ITUser@email.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53038d4e-7b6d-4185-8e7f-2415763a63d5",
                            Email = "CSUser@email.com",
                            EmailConfirmed = true,
                            Faculty = "Computer Science",
                            LockoutEnabled = true,
                            NormalizedEmail = "CSUSER@EMAIL.COM",
                            NormalizedUserName = "CSUSER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC2lBMmzn9Yz4SZc01Pp0gtWDaUXyEYFQkFmprsa93UzlO5IoXSktJ6WnO2wfzBAtw==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "YO6SY4A2FLBOS7ZHD4GRYTXZTKCD4JOM",
                            TwoFactorEnabled = false,
                            UserName = "CSUser@email.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5288bb02-53b6-47cf-9da5-a21eb80b3b13",
                            Email = "EUser@email.com",
                            EmailConfirmed = true,
                            Faculty = "Economics",
                            LockoutEnabled = true,
                            NormalizedEmail = "EUSER@EMAIL.COM",
                            NormalizedUserName = "EUSER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJo3QDCo6vtJ6l1GW3RaXbYL0+jKR+Tp8/x+Ny1VoAJhh/Mb2c+JOEA3MF0K68wkUg==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "7ASQ2UGT33TIBBIGWOHIZRSTT3ZZWSHA",
                            TwoFactorEnabled = false,
                            UserName = "EUser@email.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "893122b9-115a-41c3-b526-fc7cda035a6b",
                            Email = "ESUser@email.com",
                            EmailConfirmed = true,
                            Faculty = "Environmental Science",
                            LockoutEnabled = true,
                            NormalizedEmail = "ESUSER@EMAIL.COM",
                            NormalizedUserName = "ESUSER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECmJwOOIUtxINztEbzdBGoIv8vic33hW/XaXWx524PnHCzAq0+r9h8qXWflV9dAreA==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "ZDEUN3C3CICWEQN6KH4AI3UFWJCWGA5A",
                            TwoFactorEnabled = false,
                            UserName = "ESUser@email.com"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99b4129c-6f43-4332-80e8-1abfd403d54f",
                            Email = "PsyUser@email.com",
                            EmailConfirmed = true,
                            Faculty = "Psychology",
                            LockoutEnabled = true,
                            NormalizedEmail = "PSYUSER@EMAIL.COM",
                            NormalizedUserName = "PSYUSER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELRnJOAVIaxsmhQAwr4S4MghTgxv8ZKuJVGGcIhRaHb55dkpwnwYC86GlM9qGthE4A==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "XCVBJEVYK3X2AO3N26IMH2LTVOXNPWEN",
                            TwoFactorEnabled = false,
                            UserName = "PsyUser@email.com"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2a383ab-3759-4516-9107-fd7b075d1f23",
                            Email = "Manager@email.com",
                            EmailConfirmed = true,
                            Faculty = "Information Tecnology",
                            LockoutEnabled = true,
                            NormalizedEmail = "MANAGER@EMAIL.COM",
                            NormalizedUserName = "MANAGER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM+mPvVomCRp2EY60mU1dycFTYnWTmGIzkvnWy1R47/zs5zd9zIrRO2uDgX/wJoJmw==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "OK5EHYUMTYTQDEY5FHJVZMIYUYUYXMP2",
                            TwoFactorEnabled = false,
                            UserName = "Manager@email.com"
                        });
                });

            modelBuilder.Entity("EduPost.Models.UserReaction", b =>
                {
                    b.Property<int>("UserReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserReactionId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("article_id");

                    b.Property<bool>("ReactionType")
                        .HasColumnType("bit")
                        .HasColumnName("reaction_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserReactionId");

                    b.HasIndex("ArticleId");

                    b.ToTable("UserReaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EduPost.Models.Article", b =>
                {
                    b.HasOne("EduPost.Models.User", "User")
                        .WithMany("Article")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPost.Models.Comment", b =>
                {
                    b.HasOne("EduPost.Models.Article", null)
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduPost.Models.FeedBack", b =>
                {
                    b.HasOne("EduPost.Models.Article", null)
                        .WithMany("FeedBacks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduPost.Models.File", b =>
                {
                    b.HasOne("EduPost.Models.Article", "Article")
                        .WithMany("Files")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Article");
                });

            modelBuilder.Entity("EduPost.Models.UserReaction", b =>
                {
                    b.HasOne("EduPost.Models.Article", null)
                        .WithMany("UserReactions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EduPost.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EduPost.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EduPost.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EduPost.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPost.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EduPost.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduPost.Models.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FeedBacks");

                    b.Navigation("Files");

                    b.Navigation("UserReactions");
                });

            modelBuilder.Entity("EduPost.Models.User", b =>
                {
                    b.Navigation("Article");
                });
#pragma warning restore 612, 618
        }
    }
}
